### ISSUE TITLE
Error: std::invalid_argument & std::out_of_range

### ISSUE THREAD

**Issue by timmocking** [COMBINE-lab/maximum-likelihood-relatedness-estimation#14]
Hello, I'm having a problem using your program with my data.
My data consists of 14 samples that were sequenced low-coverage (Ion Proton). The mean coverage for these sample is around 0.8-1.2. 
Because this organism hadn't been sequenced before I had to supply a reference genome which I did by constructing +/- 130.0000 contigs from deep sequencing.
I used freebayes for SNP discovery and I filtered only on minor allele frequency and absence of indels, like you suggested.  Using your program, i get the following errors depending on the filtering i use:

terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi
Aborted (core dumped)

Or

terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr
Aborted (core dumped)

Using only a small subset of SNPs did not resolve the problem. How can I resolve this?

**Comment by kveeramah** [comment]
Can you tell us a bit more about your input vcf file? ? Does it have the required fields (GT and PL)? Perhaps if you could provide a small sample of the file.

--
Krishna R Veeramah, Ph.D.
Assistant Professor
Dept of Ecology and Evolution
Stony Brook University
Rm 616, 650 Life Sciences Building
Stony Brook
NY 11794-5245
Office: 631-632-1101
Cell: 510-207-1424
E-mail: krishna.veeramah@stonybrook.edu
http://life.bio.sunysb.edu/ee/veeramahlab

**Comment by timmocking** [comment]
Thank you for the quick response!
Looking again I get different errors depending on the vcf file I use.
I used freebayes to get a "raw" file containing all variants (SNPs, indels etc.). I did not filter on quality or anything using freebayes.

If I run mclkin with this unfiltered file, it runs for about 5 minutes until the following happens:

[jointLog] [info] Genotype likelihood format is RAW
[jointLog] [info] Parsed variants at 11061869 total sites
[jointLog] [info] allele freqs = 11061869
[jointLog] [info] gt likelihoods = 11061869
number of SNPs masked (freq 0) = 308843
number of SNPs masked (freq 1) = 466907
Calculating Prestored IBS|IBD
Starting Pairwise IBD Computations
Segmentation fault (core dumped)

When I filter this "raw" file with VCFtools VCFtools (0.1.15) on minor allele frequencies < 0.3 and removing indels. I get the following error:

[jointLog] [info] Genotype likelihood format is RAW
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi
Aborted (core dumped)

Both the raw VCF file containing unfiltered variants and the filtered file have a GT and GL field but no PL field. Could this be due to the fact I used freebayes and not another tool?

This is an example from the raw vcf file for one position:

S01_R1_paired_(paired)_contig_1 2674    .       G       A       0.24476 .       AB=0;ABP=0;AC=2;AF=0.1;AN=20;AO=2;CIGAR=1X;DP=22;DPB=22;DPRA=0.9;EPP=7.35324;EPPR=4.74748;GTI=0;LEN=1;MEANALT=1;MQM=92;MQMR=92.25;NS=10;NUMALT=1;ODDS=2.85744;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=54;QR=547;RO=20;RPL=2;RPP=7.35324;RPPR=4.74748;RPR=0;RUN=1;SAF=0;SAP=7.35324;SAR=2;SRF=10;SRP=3.0103;SRR=10;TYPE=snp     GT:DP:AD:RO:QR:AO:QA:GL 0/0:3:3,0:3:82:0:0:0,-0.90309,-7.65333  0/0:2:2,0:2:53:0:0:0,-0.60206,-5.035   0/0:4:4,0:4:113:0:0:0,-1.20412,-10.4525 .       1/1:2:0,2:0:0:2:54:-5.13,-0.60206,0   0/0:2:2,0:2:53:0:0:0,-0.60206,-5.035     .       0/0:1:1,0:1:25:0:0:0,-0.30103,-2.5      .       0/0:1:1,0:1:27:0:0:0,-0.30103,-2.7     0/0:1:1,0:1:28:0:0:0,-0.30103,-2.8      0/0:5:5,0:5:139:0:0:0,-1.50515,-12.788  0/0:1:1,0:1:27:0:0:0,-0.30103,-0.398692

**Comment by rob-p** [comment]
Hi @timmocking ,

  So the segfault shouldn't happen (clearly).  However, the error you're getting with the filtered file is interesting.  It's saying that it's attempting to convert some field to an integer `stoi()` is "string to integer", but the argument it is being passed is invalid.  This could be due to a parsing issue with the underlying library we use for VCF parsing, or with some invalid assumption we're making about a field type.  If it's in our code, it looks like the calls to stoi() are [here](https://github.com/COMBINE-lab/maximum-likelihood-relatedness-estimation/blob/93b8618554cb25b24d813ba07fed9320c55e0636/src/relatedness.cpp#L164) and [here](https://github.com/COMBINE-lab/maximum-likelihood-relatedness-estimation/blob/93b8618554cb25b24d813ba07fed9320c55e0636/src/relatedness.cpp#L348).

  Out of curiosity, could you see if you get the same behavior using the develop branch instead of master?

**Comment by timmocking** [comment]
Sorry for the late reply but my project has moved in another direction. I'm an undergraduate with very little bioinformatics experience so even this troubleshooting costs me immense amounts of time. Thank you for your help.
