### ISSUE TITLE
Allow pre-computed allele frequencies

### ISSUE THREAD

**Issue by kveeramah** [COMBINE-lab/maximum-likelihood-relatedness-estimation#5]
When sample sizes are small for the test data set, it would not be appropriate to compute allele frequencies from the samples in the vcf. In this case we should provide an option to allow external allele frequencies. I have implemented this in a python script locally, where an additional file is provided to lcMLkin with the following structure:
chromosome, position, ref allele frequency, alternate allele frequency.

I will upload the python code into the python source directory ("lcMLkin_optim_customAF.py").

The changes to the original python code are very simply and occur at lines 142-168. It’s probably a good idea to put some extra check that the SNPs in the SNP file match the same chromosome position and alleles as in the original VCF.

**Comment by rob-p** [comment]
This has been implemented on the [develop](https://github.com/COMBINE-lab/maximum-likelihood-relatedness-estimation/tree/develop) branch.  I'll merge the changes back into the master branch along with bootstrapping and some other improvements / fixes.
