### ISSUE TITLE
Error if vcf doesn't start with sample info

### ISSUE THREAD

**Issue by kveeramah** [COMBINE-lab/maximum-likelihood-relatedness-estimation#8]
Just noticed that if you run a file where the first line is not the sample info, then lcMKkin will crash. This is quite an important change as many vcf creators will produce files with these leading information lines.

Many vcf creators will have a  bunch of other stuff at the beginning of the vcf, indicated by a leading double hash. The sample info is indicated by only a single hash. 

For example a vcf file might be like so:
## More GATKstuff
# CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  SAMPLE1 SAMPLE2

We want to ignore those double hashes and only start reading the single hash as the first line with the sample name info.

**Comment by rob-p** [comment]
@kveeramah; do you have a file that you can test this on to confirm that my fix addresses this crash.  The "correct" eventual solution is to rely on a proper VCF parsing library (I've started integrating [vcflib](https://github.com/ekg/vcflib)), but this should fix this problem for the time being.

**Comment by kveeramah** [comment]
I have two test files that i'll upload into 'data'. One with extra double hashes and one without. Otherwise the genotype information is the same.

**Comment by kveeramah** [comment]
FYI, I'm getting a core dump with this new version of lcMLkin using both a file with no extra double hashes and with extra double hashes.

**Comment by rob-p** [comment]
OK -- I'm looking into it now.

**Comment by rob-p** [comment]
I just pushed a commit that I believe fixes this (I tested with the VCF both with and without the extra header).

**Comment by kveeramah** [comment]
Works for me as well. This seems resolved.

**Comment by rob-p** [comment]
Great; closing this issue and turning attention to another ;P.
